platform :ios, '10.0'

target 'Example' do
  use_frameworks!

  # Pods for Example
  pod 'LazyOnes', :path => '../'

  target 'ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
